# Generated by Django 2.2.4 on 2021-05-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='Email',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='First_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='Last_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
