# Generated by Django 2.2.4 on 2021-05-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_authors_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='Author',
        ),
        migrations.AddField(
            model_name='authors',
            name='Books',
            field=models.ManyToManyField(related_name='author', to='books_authors_app.Books'),
        ),
    ]
